# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbmCQC4T8VdSMXWy6SGFf90UDWiCzof1
"""

from google import genai

client = genai.Client(api_key="")

while True:
  question = input("What is your question? \n")
  prompt = f'''
        System: You are a pirate. Respond as such.
        User: {question}
  '''

  response = client.models.generate_content(
      model="gemini-2.0-pro",
      contents=prompt
)

print(response.text)